services:
  app:
    build: ./.docker
    container_name: app
    volumes:
      - .:/app
      - ~/.gitconfig:/home/ubuntu/.gitconfig
      - ~/.git-credentials:/home/ubuntu/.git-credentials
      - ~/.bash_aliases:/home/ubuntu/.bash_aliases
    networks:
      - devstation_network

  mariadb:
    image: mariadb:11.4.5
    container_name: mariadb-dev
    environment:
      MYSQL_DATABASE: devstation
      MYSQL_USER: devstation
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: moztopia_secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    networks:
      - devstation_network
    volumes:
      - ./.docker/mariadb/data:/var/lib/mysql

  nginx:
    container_name: nginx-dev
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - devstation_network

  redis:
    image: redis:7.4
    container_name: redis-dev
    ports:
      - "6379:6379"
    networks:
      - devstation_network
    volumes:
      - ./.docker/redis/data:/data

networks:
  devstation_network:
    driver: bridge
