version: "3.8"

services:
  app:
    build: ./.docker
    container_name: ${APP_CONTAINER_NAME}
    volumes:
      - .:/app
      - ~/.gitconfig:/home/ubuntu/.gitconfig
      - ~/.git-credentials:/home/ubuntu/.git-credentials
      - ~/.bash_aliases:/home/ubuntu/.bash_aliases
    networks:
      - ${NETWORK_NAME}

  mariadb:
    image: mariadb:${MARIADB_IMAGE_VERSION}
    container_name: ${MARIADB_CONTAINER_NAME}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MARIADB_PORT}:${MARIADB_PORT}"
    networks:
      - ${NETWORK_NAME}
    volumes:
      - ./.docker/mariadb/data:/var/lib/mysql

  nginx:
    container_name: ${NGINX_CONTAINER_NAME}
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    networks:
      - ${NETWORK_NAME}

  redis:
    image: redis:${REDIS_IMAGE_VERSION}
    container_name: ${REDIS_CONTAINER_NAME}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - ${NETWORK_NAME}
    volumes:
      - ./.docker/redis/data:/data

networks:
  devstation_network:
    driver: bridge
